apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: flakron-nginx
    training: appstellar
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      training: appstellar
  template:
    metadata:
      labels:
        training: appstellar
    spec:
      containers:
      - name: nginx
        image: nginx