namespace: nextjs-namespace
appName: flakron-next-app
app: nextjs
replicas: 3
imagePullPolicy: IfNotPresent
imageName: flakron-tag
imageTag: latest
containerPort: 3000
livenessProbe:
  initalDelaySeconds: 15
  periodSeconds: 20